-- MySQL Script generated by MySQL Workbench
-- Wed May  1 19:48:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `pin` INT NOT NULL,
  `wage` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `wage`, `pin`, `name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Time_Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Time_Card` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Time_Card` (
  `id` INT NOT NULL,
  `time_in` INT NOT NULL,
  `time_out` INT NOT NULL,
  `employee_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `employee_id_idx` (`employee_id` ASC),
  CONSTRAINT `employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`Employee` (`id`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Report` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Report` (
  `id` INT NOT NULL,
  `start_time` INT NOT NULL,
  `end_time` INT NOT NULL,
  `hours_worked` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `hours_worked`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paycheck`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Paycheck` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Paycheck` (
  `id` INT NOT NULL,
  `amount` FLOAT NOT NULL,
  `employee_wage` FLOAT NULL,
  `report_hours_worked` FLOAT NULL,
  `employee_id` INT NULL,
  `report_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `eid_idx` (`employee_id` ASC),
  CONSTRAINT `eid`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rid`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Includes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Includes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Includes` (
  `id` INT NOT NULL,
  `time_card_id` INT NOT NULL,
  `report_id` INT NULL,
  PRIMARY KEY (`id`, `time_card_id`),
  INDEX `time_card_id_idx` (`time_card_id` ASC),
  INDEX `report_id_idx` (`report_id` ASC),
  CONSTRAINT `time_card_id`
    FOREIGN KEY (`time_card_id`)
    REFERENCES `mydb`.`Time_Card` (`id`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `report_id`
    FOREIGN KEY (`report_id`)
    REFERENCES `mydb`.`Report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Login` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `id` INT NOT NULL,
  `session_id` INT NOT NULL,
  `expiration` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `company_id_idx` (`company_id` ASC),
  CONSTRAINT `company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`Company` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Controls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Controls` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Controls` (
  `id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `report_id` INT NOT NULL,
  `time_card_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `report_id`, `time_card_id`, `company_id`),
  INDEX `report_id_idx` (`report_id` ASC),
  INDEX `time_card_id_idx` (`time_card_id` ASC),
  INDEX `cid_idx` (`company_id` ASC),
  INDEX `eid_idx` (`employee_id` ASC),
  CONSTRAINT `cid`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`Login` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `empid`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `repid`
    FOREIGN KEY (`report_id`)
    REFERENCES `mydb`.`Report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tcid`
    FOREIGN KEY (`time_card_id`)
    REFERENCES `mydb`.`Time_Card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
